/*
 * JavaScript feature probes. Each snippet throws (or fails to parse) when the
 * feature is unavailable. blog8/blog9 are the verdicts from
 * https://cloudblogger.co.in/2025/11/23/orchestrator-rhino-engine-8-x-vs-9-x-comprehensive-guide-to-modern-javascript-in-vro/
 * (per-section results where a section exists, otherwise the table), so the
 * matrix shows where the real engine disagrees with the post.
 */
module.exports = [
    { name: "Arrow functions", blog8: "no", blog9: "yes", code: "var f = (a, b) => a + b; return f(1, 2);" },
    { name: "Classes", blog8: "no", blog9: "no", code: "class A { m() { return 1; } } return new A().m();" },
    { name: "Template literals", blog8: "no", blog9: "yes", code: "var n = 'x'; return `a${n}b`;" },
    { name: "String.raw", blog8: "no", blog9: "yes", code: "return String.raw`a\\nb`;" },
    { name: "BigInt", blog8: "no", blog9: "yes", code: "return String(9007199254740991n + 1n);" },
    { name: "Object destructuring (shorthand)", blog8: null, blog9: null, code: "var o = {a: 1, b: 2}; var {a, b} = o; return a + b;" },
    { name: "Object destructuring with defaults", blog8: "no", blog9: "no", code: "var o = {}; var {c = 'USA'} = o; return c;" },
    { name: "Object destructuring (rename, nested)", blog8: null, blog9: null, code: "var u = {d: {n: 'A'}}; var {d: {n: nm}} = u; return nm;" },
    { name: "Array destructuring", blog8: null, blog9: null, code: "var [x, y] = [1, 2]; return x + y;" },
    { name: "Default parameters", blog8: "no", blog9: "no", code: "function g(a = 1) { return a; } return g();" },
    { name: "Rest parameters", blog8: "no", blog9: "yes", code: "function s(...n) { return n.length; } return s(1, 2, 3);" },
    { name: "Spread in array literal", blog8: "no", blog9: "no", code: "var a = [1, 2]; return [...a, 3].length;" },
    { name: "Spread in call", blog8: "no", blog9: "no", code: "return Math.max(...[1, 5, 3]);" },
    { name: "let / const", blog8: null, blog9: "yes", code: "const PI = 3; let x = 1; { let x = 2; } return PI + x;" },
    { name: "for...of", blog8: "no", blog9: "yes", code: "var s = 0; for (var v of [1, 2, 3]) s += v; return s;" },
    { name: "for (var [k, v] of map)", blog8: "no", blog9: "yes", code: "var m = new Map([['a', 1]]); var s = 0; for (var [k, v] of m) s += v; return s;" },
    { name: "for (const x of ...)", blog8: null, blog9: null, code: "var s = 0; for (const x of [1, 2]) s += x; return s;" },
    { name: "for (const [k, v] of map)", blog8: null, blog9: null, code: "var m = new Map([['a', 1]]); var s = 0; for (const [k, v] of m) s += v; return s;" },
    { name: "for (let [k, v] of map)", blog8: null, blog9: null, code: "var m = new Map([['a', 1]]); var s = 0; for (let [k, v] of m) s += v; return s;" },
    { name: "Map / Set", blog8: "no", blog9: "yes", code: "var m = new Map(); m.set('a', 1); return m.get('a') + new Set([1, 1, 2]).size;" },
    { name: "Promise", blog8: "no", blog9: "yes", code: "return typeof Promise.resolve(1).then;" },
    { name: "Promise.finally", blog8: "no", blog9: "yes", code: "return typeof Promise.resolve(1).finally;" },
    { name: "Promise.allSettled", blog8: "no", blog9: "yes", code: "return typeof Promise.allSettled;" },
    { name: "Legacy generators (JS 1.7 yield)", blog8: "yes", blog9: null, code: "function g() { yield 1; } return g().next();" },
    { name: "Generators (function*)", blog8: null, blog9: "yes", code: "function* g() { yield 1; } return g().next().value;" },
    { name: "Symbol", blog8: "no", blog9: "yes", code: "return typeof Symbol('x');" },
    { name: "Proxy", blog8: "no", blog9: "no", code: "var p = new Proxy({}, {}); return typeof p;" },
    { name: "Reflect", blog8: "no", blog9: null, code: "var o = {}; Reflect.set(o, 'x', 42); return o.x;" },
    { name: "Exponentiation (**)", blog8: "no", blog9: "yes", code: "return 2 ** 10;" },
    { name: "Array.prototype.includes", blog8: "no", blog9: "yes", code: "return [1, 2, 3].includes(2);" },
    { name: "async / await", blog8: "no", blog9: "no", code: "async function f() { return 1; } return typeof f;" },
    { name: "Object.values / entries", blog8: "no", blog9: "yes", code: "return Object.values({a: 1}).length + Object.entries({b: 2}).length;" },
    { name: "Object.getOwnPropertyDescriptors", blog8: "no", blog9: "yes", code: "return typeof Object.getOwnPropertyDescriptors({a: 1}).a;" },
    { name: "String padStart / padEnd", blog8: "no", blog9: "yes", code: "return '4'.padStart(3, '0') + '4'.padEnd(3, '-');" },
    { name: "Array.flat / flatMap", blog8: "no", blog9: "yes", code: "return [1, [2, [3]]].flat(2).length + [1].flatMap(function (x) { return [x, x]; }).length;" },
    { name: "Object.fromEntries", blog8: "no", blog9: "yes", code: "return Object.fromEntries([['a', 1]]).a;" },
    { name: "Optional catch binding", blog8: "no", blog9: "yes", code: "try { throw 1; } catch { return 'caught'; }" },
    { name: "String.trimStart / trimEnd", blog8: "no", blog9: "yes", code: "return '  x  '.trimStart().trimEnd();" },
    { name: "Optional chaining (?.)", blog8: "no", blog9: "no", code: "var o = {}; return o?.a?.b;" },
    { name: "Nullish coalescing (??)", blog8: "no", blog9: "no", code: "var v = null; return v ?? 'd';" },
    { name: "Logical assignment (||=)", blog8: "no", blog9: "no", code: "var a = 0; a ||= 5; return a;" },
    { name: "Numeric separators", blog8: "no", blog9: "yes", code: "return 1_000_000;" },
    { name: "String.replaceAll", blog8: "no", blog9: "yes", code: "return 'a,b,c'.replaceAll(',', '|');" },
    { name: "Array.prototype.at", blog8: "no", blog9: "yes", code: "return [10, 20, 30].at(-1);" },
    { name: "Object.hasOwn", blog8: "no", blog9: "yes", code: "if (Object.hasOwn({a: 1}, 'a') !== true) throw new Error('x'); return 1;" },
    { name: "globalThis", blog8: "no", blog9: "yes", code: "if (typeof globalThis !== 'object') throw new Error(typeof globalThis); return 1;" },
    { name: "Error.stack", blog8: "no", blog9: "yes", code: "try { throw new Error('x'); } catch (e) { if (typeof e.stack !== 'string' || !e.stack.length) throw new Error('no stack'); return e.stack; }" },
    { name: "Regex sticky flag (y)", blog8: "no", blog9: null, code: "if (/a/y.sticky !== true) throw new Error('no sticky'); return 1;" },
    { name: "Regex unicode flag (u)", blog8: "no", blog9: "no", code: "return /\\u{1F600}/u.test('x');" },
    { name: "Number.EPSILON", blog8: "no", blog9: "yes", code: "if (!(Number.EPSILON > 0)) throw new Error('undefined'); return Number.EPSILON;" },
    { name: "Intl", blog8: "no", blog9: "no", code: "return new Intl.NumberFormat('en-US').format(3500);" },
    { name: "console.log", blog8: "no", blog9: "yes", code: "console.log('hi'); return 1;" },
    { name: "Array comprehensions (JS 1.7)", blog8: "yes", blog9: "yes", code: "return [i * 2 for each (i in [1, 2, 3])].length;" },
    { name: "for each...in (JS 1.6)", blog8: "yes", blog9: "yes", code: "var s = 0; for each (var v in [1, 2]) s += v; return s;" },
    { name: "E4X (XML literals)", blog8: "yes", blog9: "yes", code: "var x = <a><b>1</b></a>; return x.b.toString();" },
    { name: "Java HashMap property access", blog8: null, blog9: "yes", code: "var m = new java.util.HashMap(); m.put('k1', 'v1'); if (m.k1 !== 'v1') throw new Error('m.k1 = ' + m.k1); return m.k1;" },
    { name: "delete on java.util.ArrayList", blog8: null, blog9: "no", code: "var l = new java.util.ArrayList(); l.add('a'); l.add('b'); delete l[1]; if (l.size() !== 1) throw new Error('size still ' + l.size()); return 1;" },
    { name: "JSON superset (U+2028 in string)", blog8: "no", blog9: null, code: "return eval('\"\\u2028\"').length;" }
];
